<?php

namespace api\modules\v1\controllers;

use yii\web\Controller;

/**
 * Default controller for the `v1` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
//        $this->layout = false;
//        return $this->render('index');
        echo '111';
    }

    /**
     * @param \yii\base\Action $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        echo 'beforeAction<br/>';


        return parent::beforeAction($action); // TODO: Change the autogenerated stub


    }

    /**
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     */
    public function afterAction($action, $result)
    {
        echo 'afterAction<br/>';

        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }


}
