<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/13
 * Time: 11:23
 */

namespace api\modules\v1\controllers;

use yii\rest\ActiveController;


class UserController extends ActiveController
{
    public $modelClass = 'common\models\User';
    public $serializer = [
        'class' => 'yii\rest\Serializer',
        'collectionEnvelope' => 'items',
    ];

//    public function afterAction($action, $result)
//    {
//        \Yii::$app->response->format = 'json';
//        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
//    }
//

}