<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2016/10/31
 * Time: 17:37
 */

namespace common\widgets;


use yii\base\Widget;

class HelloWidget extends Widget
{
    public $msg =  '';


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}