<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/20
 * Time: 19:09
 */

namespace frontend\behavior;


use yii\base\Behavior;

class MyBehavior extends Behavior
{
    /**
     * @var
     */
    public $title;

    /**
     * @inheritdoc
     */
    public function behaviorMethod()
    {
        echo '这是行为类里面的方法<br/>';
    }

    /**
     * @return array
     */
    public function events()
    {
//        return parent::events(); // TODO: Change the autogenerated stub
        return [
            'wang'  => 'shout'
        ];

    }

    /**
     * @return string
     */
    public function method2()
    {
        return '通过attached 绑定行为调用';
    }

    /**
     * @param $event
     * @return string
     */
    public function shout($event)
    {
        echo '行为里面的事件调用';
    }
}