<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/1
 * Time: 16:48
 */

namespace backend\models;


use yii\base\Model;

class ItemForm extends Model
{
    /**
     * @var
     */
    public $name;
    /**
     * @var
     */
    public $type;
    /**
     * @var
     */
    public $description;

    const T_ROLE  = 1; // 角色
    const T_POWER = 2; // 权限

    /*定义场景*/

    const SCENARIOS_CREATE = 'create';
    const SCENARIOS_DELETE = 'delete';

    /**
     * @return array
     */
    public function rules()
    {
//        return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [[ 'name', 'type'], 'required'],
            [ 'name', 'unique', 'targetClass' => '\common\models\AuthItem', 'message' => '此名称已经被占用。' ],
            [ 'type', 'integer'],
            [[ 'name', 'description'], 'string', 'max'=>25]
        ];

    }

    /**
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'name' => '名称',
            'type' => '类型',
            'description' => '描述',
        ];
    }

    /**
     * 场景设置
     * @see \yii\base\Model::scenarios()
     */
    public function scenarios(){
        $scenarios = [
            self:: SCENARIOS_CREATE => ['name', 'type', 'description'],
            self:: SCENARIOS_DELETE => [ 'name'],
        ];
        return array_merge( parent:: scenarios(), $scenarios);
    }


}