<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/2/9
 * Time: 16:26
 */

namespace frontend\controllers\base;


use yii\web\Controller;

class BaseController extends Controller
{
    public function beforeAction($action)
    {
        if (!parent::beforeAction($action))
        {
            return false;
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}